version: '3'
services:

  db:
    container_name: db
    image: postgres:latest
    volumes:
      - /volumes/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_USER=denis
      - POSTGRES_PASSWORD=denis
      - POSTGRES_DB=magazine
    ports:
      - "5433:5432"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge